metaDataFormat: "yaml"
disableHugoGeneratorInject: true
baseURL: "https://www.fxsitecompat.com/"
defaultContentLanguage: "en-ca"
defaultContentLanguageInSubdir: true
hasCJKLanguage: true
disablePathToLower: true
copyright: "Kohei Yoshino and individual contributors."

taxonomies:
    category: "categories"
    version: "versions"
    status: "statuses"

params:
    Domain: "FxSiteCompat.com"
    Author:
        Name: "Kohei Yoshino"
        Email: "webmaster@fxsitecompat.com"
        GoogleUserName: "KoheiYoshino"
        TwitterUserName: "koyoskeh"
        FacebookID: "100003919776216"
        FacebookUserName: "kohei.yoshino.aqr"
    Publisher:
        GoogleUserName: "FxSiteCompatibility"
        TwitterUserName: "FxSiteCompat"
        FacebookID: "633917723366737"
        FacebookUserName: "FxSiteCompat"
    GoogleSiteSearchID: "006388931142546140887:uidl4-zslfu"

Languages:
    en-ca:
        languageCode: "en-CA"
        languageName: "English"
        weight: 1
        title: "Firefox Site Compatibility"
        GoogleSiteSearchLangCode: "en"
        FacebookLangCode: "en_US"
        DateFormat:
            Localized: "January 2, 2006"
            ISO8601: "2006-01-02T15:04:05-07:00"
        menu:
            main:
                - name: "Home"
                  weight: 1
                  identifier: "home"
                  url: "/"
                - name: "Blog"
                  weight: 2
                  identifier: "blog"
                  url: "/blog/"
                - name: "Documents"
                  weight: 3
                  identifier: "docs"
                  url: "/docs/"
                - name: "About"
                  weight: 4
                  identifier: "about"
                  url: "/about/"
                - name: "Contribute"
                  weight: 5
                  identifier: "contribute"
                  url: "/contribute/"
            syndication:
                - name: "Feed"
                  weight: 1
                  identifier: "feed"
                  url: "/index.xml"
            external:
                - name: "Twitter"
                  weight: 1
                  identifier: "twitter"
                  url: "https://twitter.com/FxSiteCompat"
                - name: "Facebook"
                  weight: 2
                  identifier: "facebook"
                  url: "https://www.facebook.com/FxSiteCompat"
                - name: "Google+"
                  weight: 3
                  identifier: "google-plus"
                  url: "https://plus.google.com/+FxSiteCompatibility"
                - name: "GitHub"
                  weight: 4
                  identifier: "github"
                  url: "https://github.com/fxsitecompat"
    ja:
        languageCode: "ja"
        languageName: "日本語"
        title: "Firefox サイト互換性情報"
        weight: 2
        GoogleSiteSearchLangCode: "ja"
        FacebookLangCode: "ja_JP"
        DateFormat:
            Localized: "2006 年 1 月 2 日"
            ISO8601: "2006-01-02T15:04:05-07:00"
        menu:
            main:
                - name: "ホーム"
                  weight: 1
                  identifier: "home"
                  url: "/"
                - name: "ブログ"
                  weight: 2
                  identifier: "blog"
                  url: "/blog/"
                - name: "ドキュメント"
                  weight: 3
                  identifier: "docs"
                  url: "/docs/"
                - name: "概要"
                  weight: 4
                  identifier: "about"
                  url: "/about/"
                - name: "協力"
                  weight: 5
                  identifier: "contribute"
                  url: "/contribute/"
            syndication:
                - name: "フィード"
                  weight: 1
                  identifier: "feed"
                  url: "/index.xml"
            external:
                - name: "Twitter"
                  weight: 1
                  identifier: "twitter"
                  url: "https://twitter.com/FxSiteCompat"
                - name: "Facebook"
                  weight: 2
                  identifier: "facebook"
                  url: "https://www.facebook.com/FxSiteCompat"
                - name: "Google+"
                  weight: 3
                  identifier: "google-plus"
                  url: "https://plus.google.com/+FxSiteCompatibility"
                - name: "GitHub"
                  weight: 4
                  identifier: "github"
                  url: "https://github.com/fxsitecompat"
