MetaDataFormat: "yaml"

ContentDir: "content/en-CA"
PublishDir: "public/en-CA"

LanguageCode: en-CA
BaseURL: "https://www.fxsitecompat.com/en-CA/"
Title: "Firefox Site Compatibility"
Copyright: "Kohei Yoshino and individual contributors."

Author:
    Name: "Kohei Yoshino"
    Email: "webmaster@fxsitecompat.com"
    GoogleUserName: "KoheiYoshino"
    TwitterUserName: "koyoskeh"
    FacebookID: "100003919776216"
    FacebookUserName: "kohei.yoshino.aqr"

Params:
    Domain: "FxSiteCompat.com"
    Publisher:
        Name: "Firefox Site Compatibility Working Group"
        GoogleUserName: "FxSiteCompatibility"
        TwitterUserName: "FxSiteCompat"
        FacebookID: "633917723366737"
        FacebookUserName: "FxSiteCompat"
    BaseDir: "/en-CA/"
    AlternateBaseDir: "/ja/"
    AlternateLangCode: "ja"
    GoogleSiteSearchID: "006388931142546140887:uidl4-zslfu"
    GoogleSiteSearchLangCode: "en"
    FacebookLangCode: "en_US"
    Locales:
         - Code: "en-CA"
           Name: "English"
         - Code: "ja"
           Name: "Japanese"
    DateFormat:
        ISO8601: "2006-01-02T15:04:05-07:00"
        Localized: "January 2, 2006"

Taxonomies:
    category: "categories"
    version: "versions"
    status: "statuses"

Menu:
    Main:
        - Name: "Home"
          Weight: 0
          Identifier: "home"
          URL: "/"
        - Name: "Blog"
          Weight: 1
          Identifier: "blog"
          URL: "/blog/"
        - Name: "Documents"
          Weight: 2
          Identifier: "docs"
          URL: "/docs/"
        - Name: "About"
          Weight: 3
          Identifier: "about"
          URL: "/about/"
        - Name: "Contribute"
          Weight: 4
          Identifier: "contribute"
          URL: "/contribute/"
    External:
        - Name: "Feed"
          Weight: 0
          Identifier: "feed"
          URL: "/index.xml"
        - Name: "Twitter"
          Weight: 1
          Identifier: "twitter"
          URL: "https://twitter.com/FxSiteCompat"
        - Name: "Facebook"
          Weight: 2
          Identifier: "facebook"
          URL: "https://www.facebook.com/FxSiteCompat"
        - Name: "Google+"
          Weight: 3
          Identifier: "google-plus"
          URL: "https://plus.google.com/+FxSiteCompatibility"
        - Name: "GitHub"
          Weight: 4
          Identifier: "github"
          URL: "https://github.com/fxsitecompat"
